---
openapi: 3.0.1
info:
  title: API V1
  version: v1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  "/authentication/login":
    post:
      summary: Logs in a user
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: successful login
        '400':
          description: invalid credentials
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      default: moyukh00145@gmail.com
                    password:
                      type: string
                      default: '1234'
              required:
              - email
              - password
        required: true
  "/users/{user_id}/posts":
    get:
      summary: Retrieves all posts for a user
      tags:
      - Posts
      security:
      - bearerAuth: []
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: posts found
        '404':
          description: user not found
    post:
      summary: Creates a post for a user
      tags:
      - Posts
      security:
      - bearerAuth: []
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '201':
          description: post created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                post:
                  type: object
                  properties:
                    title:
                      type: string
                    content:
                      type: string
              required:
              - title
              - content
  "/users/{user_id}/posts/{id}":
    get:
      summary: Retrieves a post for a user
      tags:
      - Posts
      security:
      - bearerAuth: []
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: integer
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: post found
        '404':
          description: post not found
    put:
      summary: Updates a post for a user
      tags:
      - Posts
      security:
      - bearerAuth: []
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: integer
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: post updated
        '404':
          description: post not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                post:
                  type: object
                  properties:
                    title:
                      type: string
                    content:
                      type: string
              required:
              - title
              - content
    delete:
      summary: Deletes a post for a user
      tags:
      - Posts
      security:
      - bearerAuth: []
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: integer
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: post deleted
        '404':
          description: post not found
  "/users/{user_id}/posts/create_csv":
    get:
      summary: Generates CSV for all posts of a user
      tags:
      - Posts
      security:
      - bearerAuth: []
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: CSV generated
        '404':
          description: user not found
  "/users":
    get:
      summary: Retrieves all users
      tags:
      - Users
      security:
      - bearerAuth: []
      responses:
        '200':
          description: users found
    post:
      summary: Creates a user
      tags:
      - Users
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: user created
        '400':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    first_name:
                      type: string
                    last_name:
                      type: string
                    email:
                      type: string
                    password:
                      type: string
              required:
              - first_name
              - last_name
              - email
              - password
  "/users/{id}":
    get:
      summary: Retrieves a user
      tags:
      - Users
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: user found
        '404':
          description: user not found
    put:
      summary: Updates a user
      tags:
      - Users
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: user updated
        '404':
          description: user not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    first_name:
                      type: string
                    last_name:
                      type: string
                    email:
                      type: string
                    password:
                      type: string
              required:
              - first_name
              - last_name
              - email
              - password
    delete:
      summary: Deletes a user
      tags:
      - Users
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: user deleted
        '404':
          description: user not found
  "/words/meaning":
    get:
      summary: meaning word
      tags:
      - Words
      security:
      - bearerAuth: []
      parameters:
      - name: word
        in: query
        required: true
        description: Word to get meaning
        schema:
          type: string
      responses:
        '200':
          description: successful
        '404':
          description: Word not found
  "/words/synonym":
    get:
      summary: synonym word
      tags:
      - Words
      security:
      - bearerAuth: []
      parameters:
      - name: word
        in: query
        required: true
        description: Word to get synonyms
        schema:
          type: string
      responses:
        '200':
          description: successful
        '404':
          description: Word not found
  "/documents":
    get:
      summary: list documents
      responses:
        '200':
          description: successful
    post:
      summary: create document
      responses:
        '200':
          description: successful
  "/documents/new":
    get:
      summary: new document
      responses:
        '200':
          description: successful
  "/documents/{id}/edit":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: edit document
      responses:
        '200':
          description: successful
  "/documents/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show document
      responses:
        '200':
          description: successful
    patch:
      summary: update document
      responses:
        '200':
          description: successful
    put:
      summary: update document
      responses:
        '200':
          description: successful
    delete:
      summary: delete document
      responses:
        '200':
          description: successful
  "/words":
    get:
      summary: list words
      responses:
        '200':
          description: successful
    post:
      summary: create word
      responses:
        '200':
          description: successful
  "/words/new":
    get:
      summary: new word
      responses:
        '200':
          description: successful
  "/words/{id}/edit":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: edit word
      responses:
        '200':
          description: successful
  "/words/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show word
      responses:
        '200':
          description: successful
    patch:
      summary: update word
      responses:
        '200':
          description: successful
    put:
      summary: update word
      responses:
        '200':
          description: successful
    delete:
      summary: delete word
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
